Template update
sanger-tol/ensemblgenedownload pull request #6
Opened 2023-07-15 22:14 UTC by muffato

Closes #4 
I've updated the pipeline template from 2.5 to 2.8.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/ensemblgenedownload/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-08-01 12:56 UTC, priyanka-surana requested changes
Mostly need more clarity for input parameters for ToL and non-ToL assemblies. The other comments are similar to `insdcdownload`.

2023-08-01 12:56 UTC, priyanka-surana commented on docs/usage.md
This did not work for me during testing. It kept dying on `geneset version`. Also `geneset_version` is refrenced here as both `yyyy-mm` and `yyyy_mm`. Can you clean it up?

2023-08-03 17:05 UTC, muffato commented on .nf-core.yml
I added the code of conduct and could remove this line. The rest needs to stay

2023-08-11 09:45 UTC, priyanka-surana approved these changes
LGTM 👍🏼 Thanks for making the changes.

2023-08-11 09:45 UTC, merged